### ISSUE TITLE
You probably want to link to the new built-in import tool

### ISSUE THREAD

**Issue by jexp** [idio/graphson2csv#1]
http://neo4j.com/docs/stable/import-tool.html

And provide an example for the whole roundtrip?

Thanks!

**Comment by dav009** [comment]
@jexp  Added a link to the most recent tool.
We are still working with neo4j 1.9 tools and the pipeline works alright. (Neo4jDb -> Graphson -> Neo4jDb)

For the example I'm writing, I  was unable to  get a  graphson from  neo4j `2.0.4` and  `2.1.3`.
I used different versions of the gremlin-groovy console ( `gremlin-groovy-2.6.0` and `gremlin-console-3.0.0.M7`). 
If you know a way to generate  a graphson out of the newest neo4j db versions it would be great so I can complete the example.
